### ISSUE TITLE
ADSync Not Importing

### ISSUE THREAD

**Issue by MessageGeek** [timmcmic/DLConversion#5]
Hi,

The Script appears to have difficulty importing the ADSync Module. It seems to just go in a circle, waiting for sync to finish. Populating errors at the appropriate areas, shows it can't seem to import it. When the commands are run in a separate powershell window, I can get the session to open properly, and the module to import.

Thanks,
MessageGeek

**Comment by timmcmic** [comment]
@MessgeGeek - my sincere apologies I missed this message posted here.  Do you by chance have any of the log snippets you could show me?

Tim

**Comment by MessageGeek** [comment]
No worries. I’ve since figured it out. The need for the imported logging plugin was clearly a definite requirement to getting it working. Some other questions though. Is it possible to turn off the need to have the on premises pointers (i.e the dynDL and the contact)?

Also is there a way to speed up the script? It took roughly 4 hours for 12 groups to be migrated. 

Thanks!

**Comment by timmcmic** [comment]
-convertToContact=$FALSE on the command line.   That will bypass the contact and dynamic DL logic.

I’m currently working on a switch that bypasses saving the on premises settings.  This cuts down time dramatically just for simple distribution groups.  Right now the logics not in there – so it attempts to go through and preserve any permissions set on the DL to be migrated – which is costly time wise.

The rest of it though will take time – the safety checks alone will.  I’m not opting those out because we’ve seen too many issues with other home grown solutions where things / members get missed.

Tim



Timothy J. McMichael
Senior Support Escalation Engineer
TIMMCMIC@microsoft.com<mailto:TIMMCMIC@microsoft.com>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Backup:  Chad Coker (chcoke@microsoft.com<mailto:chcoke@microsoft.com>)
Backup Hours:  Wednesday – Saturday 08:00 – 16:00 eastern time zone.

Manager:  John Sims (josims@microsoft.com<mailto:josims@microsoft.com>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

**Comment by MessageGeek** [comment]
Thank you!

**Comment by timmcmic** [comment]
If you look there’s a new branch with version 1.6 that implements the - -retainOnPremisesSettings.

This will bypass the on premises work that takes up time if you want to go and test.

I’ll have a pull request shortly.
