### ISSUE TITLE
Distribution Group converted to dynamic

### ISSUE THREAD

**Issue by hdeanmurray** [timmcmic/DLConversion#7]
Is there a reason the distribution group is converted to dynamic after moving it to the "no sync" OU in AD? Our plan is to remove these groups after all group moves are complete.

Thanks...Dean

**Comment by timmcmic** [comment]
Dean:

Yes - you can follow my blog http://TIMMCMIC.wordpress.com where I publish blog posts on the code explaining what's up.

With that being said - the dynamic distribution group is by design.  First - we needed an object on premsies that could keep the same SMTP address as the migrated distribution group.  This was to retain mail flow - allow for applications / printers / etc to email it.  

Dyanmic distribution groups worked well because they aren't touched by ad connect.  This prevents any type of proxy address collisions.

Also originally I used to keep the group.  This is where it got interesting.  So if you keep the group on premises that you migrated - and then accidentally select that OU with ad connect -> it unmigrates the group.

Tim
